import ArrowBackIos from '@material-ui/icons/ArrowBackIos';
import FastForward from '@material-ui/icons/FastForward';
import FastRewind from '@material-ui/icons/FastRewind';
import Fullscreen from '@material-ui/icons/Fullscreen';
import FullscreenExit from '@material-ui/icons/FullscreenExit';
import Pause from '@material-ui/icons/Pause';
import PersonalVideo from '@material-ui/icons/PersonalVideo';
import PlayArrow from '@material-ui/icons/PlayArrow';
import Refresh from '@material-ui/icons/Refresh';
import Search from '@material-ui/icons/Search';
import Settings from '@material-ui/icons/Settings';
import SkipNext from '@material-ui/icons/SkipNext';
import SkipPrevious from '@material-ui/icons/SkipPrevious';
import Subtitles from '@material-ui/icons/Subtitles';
export const icons = {ArrowBackIos, FastForward, FastRewind, Fullscreen, FullscreenExit, Pause, PersonalVideo, PlayArrow, Refresh, Search, Settings, SkipNext, SkipPrevious, Subtitles};
